name: test

on:
        push:
                branches: [ main ]

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v
                        - run: python hello.py
