name: test

on:
        push:
                branches: [ main ]

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - run: pytest test_example.py
